### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by cucumber-potato** [chentl/MatAL#3]
Hello Dr. Chen. 
What is the reason for the continuous error message on line 112 of the hoph.py file, as shown in the following figure
![报错](https://github.com/user-attachments/assets/74e3ca2b-816f-4885-8936-9c8fc427aeaa)
![图片](https://github.com/user-attachments/assets/051c1f09-a651-4a76-b688-f8910abd5715)

**Comment by chentl** [comment]
Hi, I was unable to locate the following line you posted from the [hpopt.py](https://github.com/chentl/MatAL/blob/fc2b9f98032f22bdd4f938c14717d014f7b235f2/hpopt.py#L112) file:   
`base_ann.model.compile(...`

It seems that the file has been modified, and it is trying to access the internal Keras model of `base_ann` (a `KerasRegressor`). If that is the case, you should use `base_ann.model_` instead of `base_ann.model` ([documentation](https://github.com/adriangb/scikeras/blob/e92a7dc466cef81b041740978cc047594fea6b4d/scikeras/wrappers.py#L81)), since the latter is only a model-building function, not the actual model itself.

**Comment by chentl** [comment]
Also as a side note, the `hpopt.py` file was used internally for hyperparameter optimization, and we uploaded it solely for reference and reproducibility. Adapting it for new projects is probably not a good idea for many reasons (e.g., it assumes a `slurm` cluster environment and uses no-longer-maintained packages such as `scikit-optimize` and `scikeras`). If you need to optimize hyperparameters for your own model, [optuna](https://optuna.org) might be a better choice.
